### PR TITLE
Remove memework from server list

### PR DESCRIPTION
**Pull request by Mstrodl**
I'd really rather you asked next time...

### CODE REVIEW

**Comment by aveao** [comment]
The invite seems to invite a lot of low quality users. Seconded.

**Comment by mralext20** [comment]
Perhaps replace it with discord.gg/code

**Comment by motiontheking** [comment]
Brought low quality users as @aveao said

**Comment by aveao** [comment]
As a sidenote, public != publicized. Even though we have a site online, it's "public", not "publicized". (the abstract [here](https://dl.acm.org/citation.cfm?id=2028045) explains the difference well)

**Comment by slice** [comment]
I agree with this change.

**Comment by lnmds** [comment]
I also agree, being the another owner of Memework.

**Comment by jacc** [comment]
deepest apologies guys, I really didn't think about it at the time of commiting it. forgive me for my mistake!

**Pull request merged**
