### PR TITLE
Added Flash Bot

### PR DESCRIPTION
**Pull request by Crypti-x**
Details: https://flashbot.de

### CODE REVIEW

**Comment by Biospheere** [comment]
Definitely not awesome

**Comment by DRSchlaubi** [comment]
I heard that this bot got deleted from discordbots
org

**Comment by GregTCLTK** [comment]
I hate this bot

**Comment by byparallax** [comment]
Heya, can you guys explain what's so bad with this bot? Looking at their website, it seems to have pretty solid features. Thanks!

**Comment by GregTCLTK** [comment]
there are a lot of reasons

**Comment by byparallax** [comment]
Such as?

**Comment by vitalkanev** [comment]
> Reasons

Perhaps please explain these

**Comment by Biospheere** [comment]
* Abusing rights of the bot
* Developer is faking Servercount on all botlists

**Comment by byparallax** [comment]
Alright, thanks. I have confirmed these issues with external sources, and therefore won't merge it.

**Pull request closed without merging**
