### PR TITLE
Separate Mods and Addons, Update Descriptions

### PR DESCRIPTION
**Pull request by justdotJS**
- Separate Mods and Addons, as Addons are allowed and Mods aren't
- Change SimplePresence description to highlight music rich presence

*Note: I created SimplePresence, that's why I think it'd be best to separate Mods and Addons, so that people don't get confused.*

### CODE REVIEW

**Comment by byparallax** [comment]
I believe that "Mods" should be switched to client modifications, and that add-ons could be a more general "tools" category. Thoughts?

**Comment by justdotJS** [comment]
To keep them short, maybe "Modifications" instead of "Client Modifications"? "Tools" seems good to me. I'll edit the PR.

**Comment by byparallax** [comment]
Perhaps Client Mods if we're looking to make it shorter? Just sending suggestions.

**Comment by justdotJS** [comment]
"Hacks" or "Injections" could also work? Not sure myself 😄.

**Comment by byparallax** [comment]
I will keep modifications in the meanwhile. Thank you for contributing!

**Comment by justdotJS** [comment]
OK, and no problem! Happy to help 👍

**Pull request merged**
