### PR TITLE
Delete the "Popular Servers" category. See desc.

### PR DESCRIPTION
**Pull request by byparallax**
Hey there; this commit is just a way to showcase the changes suggested in #15.

### CODE REVIEW

**Comment by jacc** [comment]
As of now I will keep it. Will review later.

**Comment by jacc** [comment]
@byparallax maybe add the popular servers that are r/ to Popular Subreddits

**Comment by byparallax** [comment]
As stated in the pull request for Popular Subreddits, I'd only consider discord related subreddits. It's awesome-discord after all; not awesome-reddit. It can be done, if you wish though. That's just my 2cents.

**Comment by jacc** [comment]
True. I’m gonna merge

**Comment by jacc** [comment]
I lied, theres a merge conflict.

**Comment by jacc** [comment]
@austinhuang0131 @byparallax still has a merge conflict.

**Comment by byparallax** [comment]
Hold on, I'm going to take a look.

**Comment by byparallax** [comment]
I believe I fixed it. Not sure lol.

**Comment by jacc** [comment]
@byParallax thank you as always!

**Comment by byparallax** [comment]
It's a pleasure.

**Pull request merged**
