### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Crypti-x**
2018 bois

### CODE REVIEW

**Comment by GregTCLTK** [comment]
https://github.com/jacc/awesome-discord/pull/48 👀

**Comment by Schlauer-Hax** [comment]
Heyy warum hast du mich eig gebannt?

**Comment by Schlauer-Hax** [comment]
I hate this bot

**Comment by jacc** [comment]
Please provide evidence for why these bots are being removed.

**Comment by byparallax** [comment]
As per API changes, the bots he removed are legitimately not working anymore. The websites he listed are accurate, and the ones he removed aren't in activity anymore. However, I fail to see the need to add "flashbot".

**Pull request closed without merging**
